### ISSUE TITLE
Tests fail on master branch

### ISSUE THREAD

**Issue by the-J** [cloudinary/cloudinary-video-player#124]
Ladies and gentleman, tests on master fail and I kind of can't understand why.  
```
Test Suites:   14 failed, 1 passed, 15 total
Tests:         34 failed, 2 passed, 36 total
Snapshots:     0 total
Time:          15.661s
Ran all test suites.
```

**Comment by maoznir** [comment]
Hi @the-J 
Can you please do:
git pull
yarn install
yarn run build
yarn run test
And let us know if it works for you? if not please send the full output here.

**Comment by the-J** [comment]
```
yarn test
yarn run v1.17.3
$ node webpack/pre-build.js
$ jest --no-cache --detectOpenHandles
 PASS  test/analytics.test.js (44.603s)
 PASS  test/api.test.js (39.702s)
 PASS  test/playlist.test.js
 PASS  test/ui-conf.test.js (6.698s)
 PASS  test/basic-ui.test.js (8.578s)
 PASS  test/recommendations.test.js (9.259s)
 PASS  test/colors.test.js
 PASS  test/fluid.test.js (5.737s)
 PASS  test/ads.test.js (11.831s)
 PASS  test/title-bar.test.js
 PASS  test/custom-error.test.js
 FAIL  test/multiplayer.test.js
  ● Multi-player tests › Test play

    expect(received).toBe(expected) // Object.is equality

    Expected: true
    Received: false

      18 |       let id = '#' + player.playerId + '_html5_api';
      19 |       await page.waitFor(1500);
    > 20 |       expect(await page.$eval(id, el => el.playing)).toBe(true);
         |                                                      ^
      21 |     }
      22 |   });
      23 | });

      at toBe (test/multiplayer.test.js:20:54)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

 PASS  test/components.test.js
 PASS  test/autoplay.scroll.test.js
 PASS  test/vp-unit.test.js

Test Suites: 1 failed, 14 passed, 15 total
Tests:       1 failed, 38 passed, 39 total
Snapshots:   0 total
Time:        138.182s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
Earlier analytics.test.js failed. But it is definitely  different than it was earlier. After third try all tests passed.

**Comment by maoznir** [comment]
Hi @the-J
Glad to hear all tests passed, 
I've also pushed a small fix thats makes it so you can run the tests without running build first.
If all works fine for you, I'll close this issue.
